### ISSUE TITLE
Not working with docker-compose >= 1.25.1

### ISSUE THREAD

**Issue by sglahn** [rewe-digital-incubator/frost#15]
The behavior of "ignore-pull-failures" in docker-compose has changed since 1.25.1. Frost will fail unexpectedly if the image is only available in the local registry, e.g. the CI server, but not (yet) in the remote registry.

See: https://github.com/docker/compose/issues/7127
> Please note that, if the image you refer to in your compose file that is not available on a registry do declare a build section, then compose 1.25.1 will not fail but let you know this one should be built

**Comment by stefanneuhaus** [comment]
Is there anything that we can do about this? Do you see any fixes on our side? @sglahn 

For me personally it would be fine to have this issue as a reference that links to the issue in docker-compose.
